name: Terraform-Packer-Build

on: 
  workflow_dispatch

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Packer
      env:
        PACKER_VERSION: "1.5.6"
      run: |
        VER=$PACKER_VERSION
        wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
        sudo apt install unzip
        unzip packer_${VER}_linux_amd64.zip
        sudo mv packer /usr/local/bin
    - name: Terraform create credential
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_TERRAFORM }}
      run: |
        mkdir credential
        echo $GOOGLE_APPLICATION_CREDENTIALS > credential/gcp_credentials.json
    - name: Packer Build Image
      run: |
        pwd
        ./packer/build.sh
        cat ../terraform/jenkins_imagevar.tf
